### ISSUE TITLE
Search not working REGISTRUL ANUAL DE EVIDENŢĂ A DECEDAŢILOR FĂRĂ APARŢINĂTOR

### ISSUE THREAD

**Issue by candale** [BontaVlad/ExpirationDate#2]
Trying to search on REGISTRUL ANUAL DE EVIDENŢĂ A DECEDAŢILOR FĂRĂ APARŢINĂTOR and i get an exeption:
django.core.exceptions.FieldError: Cannot resolve keyword 'number' into field. Choices are: cemetery, cemetery_id, deceased, deceased_id, funeral_date, has_funeral_constructions, id, image, owner, owner_id, parcel, position, receipt_number, row, social_services_request, surface_area

**Comment by BontaVlad** [comment]
Lasa numele exact al modelului, ii greu sa stiu exact la ce te referi

**Comment by BontaVlad** [comment]
number este o metoda pe proxy model.
No you cannot use it that way, because this only works with attributes that represent columns in the database, not with properties. The only way to make this work would be using a subclass of contrib.admin.views.main.ChangeList for the change list and overwrite it's get_query_set method to achieve the desired behaviour!

**Comment by BontaVlad** [comment]
Am scos `number` de la search term
